import json
from typing import Dict, Any


class K6Compiler:
    """
    Stage 9: Deterministic k6 Script Compiler.
    - Transforms Canonical Spec IR into clean, production-grade ES6 JavaScript.
    - Avoids arbitrary code injection through strict structural templating.
    - Emits options, stages, thresholds, HTTP requests, and assertions.
    """

    @classmethod
    def compile(cls, normalized_spec: Dict[str, Any]) -> str:
        metadata = normalized_spec.get("metadata", {})
        test_meta = normalized_spec.get("test", {})
        target = normalized_spec["target"]
        load = normalized_spec["load"]
        stages = normalized_spec.get("stages", [])
        headers = normalized_spec.get("headers", {})
        payload = normalized_spec.get("payload", {})
        thresholds = normalized_spec.get("thresholds", {})
        checks = normalized_spec.get("checks", [])

        # Build options configuration
        options_dict: Dict[str, Any] = {}

        if stages:
            options_dict["stages"] = [
                {"duration": f"{s['duration_seconds']}s", "target": s["target_vus"]}
                for s in stages
            ]
        else:
            options_dict["vus"] = load.get("target_vus", 10)
            options_dict["duration"] = f"{load.get('duration_seconds', 60)}s"

        if thresholds:
            options_dict["thresholds"] = thresholds

        options_json = json.dumps(options_dict, indent=2)

        # Build checks
        check_clauses = []
        if checks:
            for chk in checks:
                name = chk.get("name", "status ok")
                expr = chk.get("expression", "r.status === 200")
                check_clauses.append(f"    {json.dumps(name)}: (r) => {expr}")
        else:
            check_clauses.append("    'status is 200': (r) => r.status === 200")
            check_clauses.append("    'response duration < 2000ms': (r) => r.timings.duration < 2000")

        checks_code = ",\n".join(check_clauses)

        # Build request execution
        method = target.get("method", "GET").upper()
        url = f"{target['base_url']}{target['endpoint']}"

        # Method call mapping
        method_map = {
            "GET": "http.get",
            "POST": "http.post",
            "PUT": "http.put",
            "PATCH": "http.patch",
            "DELETE": "http.del",
            "HEAD": "http.head",
            "OPTIONS": "http.options"
        }
        k6_http_func = method_map.get(method, "http.request")

        # Format Payload
        has_body = method in ("POST", "PUT", "PATCH") and payload.get("body") is not None
        if has_body:
            body_val = payload["body"]
            if isinstance(body_val, (dict, list)):
                payload_code = f"const payload = JSON.stringify({json.dumps(body_val, indent=2)});"
            else:
                payload_code = f"const payload = {json.dumps(str(body_val))};"
            payload_arg = ", payload"
        else:
            payload_code = "// No request body required for this method"
            payload_arg = ", null" if method in ("POST", "PUT", "PATCH") else ""

        # Format Headers & Params
        params_code = f"const params = {{\n  headers: {json.dumps(headers, indent=4)},\n  timeout: '{target.get('timeout_ms', 10000)}ms'\n}};"

        # Format full HTTP call
        if method in ("GET", "HEAD", "OPTIONS"):
            http_call_code = f"const response = {k6_http_func}(url, params);"
        elif method in ("POST", "PUT", "PATCH"):
            http_call_code = f"const response = {k6_http_func}(url, payload, params);"
        elif method == "DELETE":
            if has_body:
                http_call_code = "const response = http.del(url, payload, params);"
            else:
                http_call_code = "const response = http.del(url, null, params);"
        else:
            http_call_code = f"const response = http.request('{method}', url{payload_arg}, params);"

        script = f"""// ==============================================================================
// Generated by Antigravity AI Validation & Compilation Pipeline
// Target: {url}
// Test Type: {test_meta.get('type', 'load')} | Contract Spec Version: {normalized_spec.get('version', '1.0')}
// Description: {metadata.get('name', 'k6 Test')}
// ==============================================================================

import http from 'k6/http';
import {{ check, sleep }} from 'k6';

export const options = {options_json};

export default function () {{
  const url = '{url}';

  {payload_code}

  {params_code}

  {http_call_code}

  check(response, {{
{checks_code}
  }});

  // Pacing pause between iterations
  sleep(1);
}}
"""
        return script.strip()
